version: '3'
services:
  db:
    image: postgres
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_DB=security
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  redis-server:
    container_name: redis
    image: 'redis'
    ports:
      - "6379:6379"
  java-service:
    build: .
    links:
      - redis-server
    ports:
      - "8085:8085"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5435/security
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create